name: Trigger auto deployment for openai-sk-chat-app-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/openai-sk-chat-app-ca-AutoDeployTrigger-dcffc143-d335-46ac-836c-da228cb2771e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OPENAISKCHATAPPCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENAISKCHATAPPCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENAISKCHATAPPCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cr3qrjt56lww43a.azurecr.io
          registryUsername: ${{ secrets.OPENAISKCHATAPPCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPENAISKCHATAPPCA_REGISTRY_PASSWORD }}
          containerAppName: openai-sk-chat-app-ca
          resourceGroup: openai-sk-chat-app-rg
          imageToBuild: cr3qrjt56lww43a.azurecr.io/openai-sk-chat-app-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


